# Generated by Django 3.2.13 on 2022-06-12 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awardsapp', '0002_remove_profile_image_profile_date_craeted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_craeted',
            new_name='date_created',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='home/')),
                ('link', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('date_craeted', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
