# Generated by Django 3.2.13 on 2022-06-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0006_rename_author_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
