# Generated by Django 3.2.13 on 2022-06-14 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awardsapp', '0011_alter_profile_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.PositiveSmallIntegerField(choices=[(1, '1 - Unsatisfactory'), (2, '2 - Pathetic'), (3, '3 - Very bad'), (4, '4 - Bad'), (5, '5 - Average'), (6, '6 - Okay'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Perfect')], default=5)),
                ('usability', models.PositiveSmallIntegerField(choices=[(1, '1 - Unsatisfactory'), (2, '2 - Pathetic'), (3, '3 - Very bad'), (4, '4 - Bad'), (5, '5 - Average'), (6, '6 - Okay'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Perfect')], default=5)),
                ('content', models.PositiveSmallIntegerField(choices=[(1, '1 - Unsatisfactory'), (2, '2 - Pathetic'), (3, '3 - Very bad'), (4, '4 - Bad'), (5, '5 - Average'), (6, '6 - Okay'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Perfect')], default=5)),
                ('comment', models.CharField(blank=True, default='', max_length=250)),
                ('overall', models.IntegerField(blank=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awardsapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
